### ISSUE TITLE
Dependency confusion supply-chain vulnerability detected

### ISSUE THREAD

**Issue by ashishbijlani** [sonnelib/sonne#1]
I'm a Cybersecurity researcher developing PackjGuard [1]. Our tool has detected a dependency confusion vulnerability in this repository.

The package `sonne` mentioned in the README at [line 10](https://github.com/sonnelib/sonne/blob/main/README.md?plain=1#L10) does not exist on public PyPI registry. A bad actor can hijack this package to propagate malicious code.

Not only your apps/service is vulnerable to this attack, but the users of your open-source Github repo are also vulnerable to this attack.

Please register a placeholder package for `sonne` on public PyPI soon to remediate.

Thanks!

PackjGuard is a Github app that monitors repos for malicious/vulnerable dependencies and mitigates attacks by creating pull requests for automatic remediation https://github.com/marketplace/packjguard

**Comment by ekinpy** [comment]
Thanks for reporting. It's fixed.
